import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nerd Pools</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      Hello Nextjs
    </div>
  );
}
